"use client";
import { useEffect, useState } from "react";
import { Wrench, RefreshCw, ShieldCheck } from "lucide-react";
import { api } from "@/lib/client";
import { RentalMessages } from "@/components/rental-messages";
import { calculateFine, dueLabel, formatRentalDate, pickupTimestamp, type Booking, type RentalMessage, type ServiceStatus } from "@/lib/rental";
export default function Manage(){
  const [ready,setReady]=useState(false);const [service,setService]=useState<ServiceStatus|null>(null);const [password,setPassword]=useState("");
  const [bookings,setBookings]=useState<Booking[]>([]);const [messages,setMessages]=useState<RentalMessage[]>([]);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [expanded,setExpanded]=useState<string|null>(null);
  async function refresh(){const data=await api<{bookings:Booking[];messages:RentalMessage[]}>("/api/staff");setBookings(data.bookings);setMessages(data.messages);}
  useEffect(()=>{api<{staff:boolean;service:ServiceStatus}>("/api/account").then(data=>{setService(data.service);setReady(data.staff);if(data.staff)return refresh();}).catch(e=>setNotice(e.message));},[]);
  async function action(run:()=>Promise<unknown>){setBusy(true);setNotice("");try{await run();}catch(e){setNotice(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
  async function transition(booking:Booking,step:"pickup"|"return"){
    if(!window.confirm(step==="pickup"?`Confirm ${booking.customerName} has collected ${booking.tool.name}?`:`Confirm ${booking.tool.name} has been returned? The final late fee is ₹${calculateFine(booking).amount}.`))return;
    await action(async()=>{await api(`/api/bookings/${booking.id}`,{action:step});await refresh();setNotice(step==="pickup"?"Pickup confirmed. The WhatsApp update is queued.":"Return confirmed. Reminders have stopped and the final fine is fixed.");});
  }
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><a href="/" className="flex items-center gap-2 text-xl font-extrabold text-blue-700"><Wrench/> Toolnest</a><span className="flex items-center gap-2 text-sm font-bold text-slate-600"><ShieldCheck size={18}/> Staff desk</span></div></header><div className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-3xl font-black">Pickup & returns</h1><p className="mt-2 text-slate-600">Confirm the handover, track return deadlines and review WhatsApp delivery.</p>
    {notice&&<p role="status" className="my-5 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-800">{notice}</p>}
    {!ready?<form className="mt-8 max-w-md rounded-2xl border border-slate-200 bg-white p-6" onSubmit={e=>{e.preventDefault();action(async()=>{await api("/api/account",{action:"staff",password});setPassword("");setReady(true);await refresh();});}}><label className="block text-sm font-bold">Staff password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required className="field mt-2 w-full"/></label><button disabled={busy||!service?.accountsReady} className="mt-4 w-full rounded-xl bg-blue-600 px-4 py-3 font-bold text-white disabled:opacity-50">{busy?"Signing in…":"Sign in"}</button>{service&&!service.accountsReady&&<p className="mt-4 text-sm text-amber-700">Account setup is pending. <a href="/setup" className="underline">View setup steps</a>.</p>}</form>:<>
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-5"><div><p className="font-bold">{bookings.filter(b=>b.status==="active").length} active rentals</p><p className="mt-1 text-sm text-slate-500">{service?.whatsappReady?"WhatsApp sending configured":"WhatsApp connection pending • messages will remain queued"}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>action(refresh)} className="flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold disabled:opacity-50"><RefreshCw size={16}/> Refresh</button><button disabled={busy} onClick={()=>action(async()=>{await api("/api/staff",{});await refresh();setNotice("Due notifications checked. Review delivery statuses below.");})} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">Check due notifications</button><button onClick={()=>action(async()=>{await api("/api/account",{action:"logout"});setReady(false);setBookings([]);setMessages([]);})} className="rounded-xl border px-4 py-2.5 text-sm font-bold">Log out</button></div></div>
    <div className="mt-6 space-y-4">{bookings.map(b=><article key={b.id} className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-bold uppercase text-blue-700">{b.status==="upcoming"?"Reserved":b.status==="previous"?"Returned":b.status}</p><h2 className="mt-1 text-xl font-extrabold">{b.tool.name}</h2><p className="mt-2 text-sm text-slate-600">{b.customerName} · {b.customerPhone} · {b.id}</p><p className="mt-1 text-sm text-slate-600">{b.shop.name} · Pickup {formatRentalDate(b.start)}, {b.pickup} IST</p><p className="mt-2 font-semibold">Return by {dueLabel(b)}</p>{calculateFine(b).amount>0&&<p className="mt-1 font-bold text-red-700">{b.status==="previous"?"Final":"Current"} fine: ₹{calculateFine(b).amount}</p>}</div><div className="flex flex-wrap items-start gap-2">{b.status==="upcoming"&&<button disabled={busy||Date.now()<pickupTimestamp(b)||Date.now()>=b.dueAt} onClick={()=>transition(b,"pickup")} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-40">Confirm pickup</button>}{b.status==="active"&&<button disabled={busy} onClick={()=>transition(b,"return")} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white disabled:opacity-40">Confirm return</button>}<button onClick={()=>setExpanded(expanded===b.id?null:b.id)} className="rounded-xl border px-4 py-3 text-sm font-bold">{expanded===b.id?"Hide":"View"} messages</button></div></div>{expanded===b.id&&<RentalMessages booking={b} messages={messages.filter(m=>m.bookingId===b.id)} connected={service?.whatsappReady??false} demo={false}/>}</article>)}{!bookings.length&&<p className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-500">New customer bookings will appear here.</p>}</div>
    </>}
    </div></main>;
}
