import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url);const {chromium}=require('playwright');
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('.sites-runtime/test-output',{recursive:true});
try{
  await page.goto('http://127.0.0.1:4173/',{waitUntil:'domcontentloaded'});
  await page.getByRole('heading',{name:'Create your account',exact:true}).waitFor();
  await page.screenshot({path:'.sites-runtime/test-output/register-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Try presentation demo',exact:true}).click();
  await page.getByLabel('Full name',{exact:true}).fill('College Presenter');
  await page.getByLabel('Mobile number',{exact:true}).fill('9876543219');
  await page.getByLabel('Password',{exact:true}).fill('demo-password-123');
  await page.getByLabel('Confirm password',{exact:true}).fill('demo-password-123');
  await page.getByRole('checkbox').check();
  await page.getByRole('button',{name:'Register account',exact:true}).click();
  await page.getByRole('heading',{name:'Welcome back',exact:true}).waitFor();
  assert.match(await page.locator('body').innerText(),/Registration successful/);
  await page.getByLabel('Password',{exact:true}).fill('demo-password-123');
  await page.getByRole('button',{name:'Log in',exact:true}).click();
  await page.getByRole('button',{name:'My Dashboard',exact:true}).waitFor();
  await page.getByRole('heading',{name:'Power Tools',exact:true}).locator('xpath=ancestor::button').click();
  await page.getByRole('heading',{name:'Drilling & Breaking',exact:true}).locator('xpath=ancestor::button').click();
  await page.getByRole('button',{name:'Book Now',exact:true}).first().click();
  await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Toolnest Bhayandar Station',exact:true})}).click();
  const future=page.locator('button[aria-label$=", available"]');
  await future.first().waitFor();
  // A one-day rental uses the same future calendar cell for start and return.
  const target=future.nth(1);await target.click();await target.click();
  await page.getByRole('button',{name:'Confirm Booking',exact:true}).click();
  await page.getByRole('heading',{name:'Your Tool is Reserved!',exact:true}).waitFor();
  assert.match(await page.locator('body').innerText(),/Preview only • not sent/);
  await page.getByRole('button',{name:'Simulate pickup',exact:true}).click();
  await page.getByRole('heading',{name:'Rental Active',exact:true}).waitFor();
  await page.getByRole('button',{name:'Preview due reminder',exact:true}).click();
  await page.getByRole('heading',{name:'Return reminder',exact:true}).waitFor();
  await page.getByRole('button',{name:'Simulate 1 day overdue',exact:true}).click();
  await page.getByText('Current fine: ₹50 (1 day)',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Add another overdue day',exact:true}).click();
  await page.getByText('Current fine: ₹100 (2 days)',{exact:true}).waitFor();
  await page.screenshot({path:'.sites-runtime/test-output/whatsapp-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'.sites-runtime/test-output/whatsapp-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'No horizontal overflow on mobile');
  await page.getByRole('button',{name:'Confirm demo return',exact:true}).click();
  await page.getByRole('heading',{name:'Rental Completed',exact:true}).waitFor();
  await page.getByText('Final fine: ₹100 (2 days)',{exact:true}).waitFor();
  await page.reload({waitUntil:'domcontentloaded'});
  await page.getByRole('button',{name:'Open dashboard',exact:true}).click();
  await page.getByRole('button',{name:/Previous Rentals/}).click();
  assert.match(await page.locator('body').innerText(),/Bosch Demolition Hammer/);
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Logout',exact:true}).click();
  await page.getByRole('heading',{name:'Create your account',exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'.sites-runtime/test-output/register-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'No horizontal overflow on mobile registration');
  await page.goto('http://127.0.0.1:4173/setup');await page.getByRole('heading',{name:'Connect WhatsApp',exact:true}).waitFor();
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('PASS Browser: registration → separate login → booking → pickup → reminder → overdue fees → return → reload persistence → logout; desktop/mobile and no runtime errors.');
}catch(e){await page.screenshot({path:'.sites-runtime/test-output/failure.png',fullPage:true});console.error((await page.locator('body').innerText()).slice(0,5500));throw e;}finally{await browser.close();}
