import assert from 'node:assert/strict';
import {randomUUID,createHmac} from 'node:crypto';
const base=process.env.TEST_BASE_URL??'http://127.0.0.1:4173';
const service='http://127.0.0.1:8877';
assert.ok(base.startsWith('http://127.0.0.1:'),'Only run against a local test server');
let assertions=0;
const check=(condition,message)=>{assert.ok(condition,message);assertions++;console.log('PASS',message);};
const redis=async(...cmd)=>{const r=await fetch(service,{method:'POST',body:JSON.stringify(cmd)});const d=await r.json();if(d.error)throw Error(d.error);return d.result;};
function client(){let cookie='';return {async req(path,data,headers={}){const r=await fetch(base+path,{method:data===undefined?'GET':'POST',headers:{Origin:base,...(data!==undefined?{'Content-Type':'application/json'}:{}),Cookie:cookie,...headers},body:data===undefined?undefined:JSON.stringify(data)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()};}};}
async function waitFor(checkFn){for(let i=0;i<50;i++){if(await checkFn())return;await new Promise(r=>setTimeout(r,150));}throw Error('Timed out waiting for background notification');}
const count=async()=> (await (await fetch(service)).json()).messages.length;
await redis('FLUSHALL');
const a=client(),b=client(),staff=client(),anonymous=client();
let r=await anonymous.req('/api/bookings');check(r.status===401,'Anonymous bookings are protected');
r=await a.req('/api/account',{action:'login',phone:'9876543210',password:'college-test-pass'});check(r.status===401,'Login cannot create an unregistered account');
r=await a.req('/api/account',{action:'register',name:'Test Student',phone:'9876543210',password:'college-test-pass',confirmPassword:'mismatch',whatsappConsent:true});check(r.status===400,'Mismatched registration passwords rejected');
r=await a.req('/api/account',{action:'register',name:'Test Student',phone:'9876543210',password:'college-test-pass',confirmPassword:'college-test-pass',whatsappConsent:true});check(r.status===201,'Registration succeeds');
const userId=r.data.account.id;
r=await a.req('/api/account');check(r.data.account===null,'Registration requires a separate login');
const stored=JSON.parse(await redis('HGET','toolnest:v1:accounts',userId));check(!JSON.stringify(stored).includes('college-test-pass')&&stored.passwordHash.length===128,'Only a salted password hash is stored');
r=await a.req('/api/account',{action:'register',name:'Test Student',phone:'+919876543210',password:'college-test-pass',confirmPassword:'college-test-pass',whatsappConsent:true});check(r.status===409,'Duplicate mobile number registration rejected');
r=await a.req('/api/account',{action:'login',phone:'9876543210',password:'wrong-password'});check(r.status===401,'Incorrect password rejected');
r=await a.req('/api/account',{action:'login',phone:'9876543210',password:'college-test-pass'});check(r.status===200&&r.data.account.phone==='+919876543210','Mobile password login succeeds');
r=await a.req('/api/account',{action:'logout'},{Origin:'https://untrusted.example'});check(r.status===403,'Cross-origin mutation rejected');
await b.req('/api/account',{action:'register',name:'Second Student',phone:'9876543211',password:'college-test-pass',confirmPassword:'college-test-pass',whatsappConsent:false});
await b.req('/api/account',{action:'login',phone:'9876543211',password:'college-test-pass'});
const epoch=Date.UTC(2026,8,1),dayMs=86400000;const india=new Date(Date.now()+19800000);const today=Math.floor((Date.UTC(india.getUTCFullYear(),india.getUTCMonth(),india.getUTCDate())-epoch)/dayMs)+1;
const tool='Bosch Demolition Hammer',shop='Toolnest Bhayandar Station';
function booked(day){const d=new Date(epoch+(day-1)*dayMs);const k=`${tool}|${shop}|${d.getUTCFullYear()}-${d.getUTCMonth()}`;const h=Array.from(k).reduce((v,c)=>(v*31+c.charCodeAt(0))>>>0,0);return [5+h%3,12+(h>>>3)%3,20+(h>>>6)%3,26+(h>>>9)%3].includes(d.getUTCDate());}
let start=today+1;while(booked(start)||booked(start+1))start++;
const input={requestId:randomUUID(),toolName:tool,categorySlug:'power-tools',sub:'Drilling & Breaking',shopName:shop,start,end:start+1,pickup:'10:00 AM – 11:00 AM',price:1,lateFeePerDay:0};
r=await a.req('/api/bookings',{...input,start:today-1});check(r.status===400,'Past pickup dates rejected server-side');
r=await a.req('/api/bookings',input);if(r.status!==201)console.error('Booking response',r);check(r.status===201,'Rental reservation saved');
let booking=r.data.booking;const id=booking.id;
check(booking.shop.price===650&&booking.lateFeePerDay===50,'Price and late fee come from server, not browser');
check(booking.dueAt===epoch+(booking.end-1)*dayMs+45000000,'Return deadline is exactly 6 PM India time');
r=await a.req('/api/bookings',input);check(r.status===201&&r.data.booking.id===id,'Retried booking request is idempotent');
r=await b.req('/api/bookings',{...input,requestId:randomUUID()});check(r.status===409,'Two customers cannot reserve the same tool/shop dates');
r=await b.req('/api/bookings');check(r.data.bookings.length===0&&r.data.messages.length===0,'Customer data is isolated');
r=await b.req(`/api/bookings/${id}`,{action:'cancel'});check(r.status===404,'Customer cannot cancel another account booking');
r=await a.req(`/api/bookings/${id}`,{action:'pickup'});check(r.status===403,'Only staff can confirm pickup');
await waitFor(async()=>await count()===1);
check(await count()===1,'One order message sent despite duplicate booking retry (mock Meta)');
let sent=(await (await fetch(service)).json()).messages;
check(sent[0].payload.to==='919876543210'&&sent[0].payload.template.name==='toolnest_order_confirmed'&&sent[0].payload.template.components[0].parameters.length===9,'Meta template recipient and parameters are correct');
r=await a.req('/api/bookings');check(r.data.messages[0].status==='accepted','API acceptance is not labelled delivered');
r=await staff.req('/api/account',{action:'staff',password:'local-staff-password-1234567890'});check(r.status===200,'Staff sign-in works');
r=await staff.req(`/api/bookings/${id}`,{action:'pickup'});check(r.status===400,'Premature live pickup blocked');
// Time passage fixture: move the saved test booking into its collection window.
booking={...booking,start:today-1,dueAt:Date.now()+3600000};await redis('HSET','toolnest:v1:bookings',id,JSON.stringify(booking));
r=await staff.req(`/api/bookings/${id}`,{action:'pickup'});check(r.status===200&&r.data.booking.status==='active','Staff pickup activates rental');
await waitFor(async()=>await count()===3);
check(await count()===3,'Pickup confirmation and near-due reminder are sent (mock Meta)');
r=await staff.req(`/api/bookings/${id}`,{action:'pickup'});check(r.status===200,'Repeated pickup is idempotent');
await staff.req('/api/staff',{});check(await count()===3,'Repeated due checks do not duplicate notices');
booking=JSON.parse(await redis('HGET','toolnest:v1:bookings',id));booking.dueAt=Date.now()-3600000;await redis('HSET','toolnest:v1:bookings',id,JSON.stringify(booking));
r=await fetch(base+'/api/cron/notifications');check(r.status===401,'Scheduler requires its secret');
r=await fetch(base+'/api/cron/notifications',{headers:{Authorization:'Bearer local-cron-secret-1234567890'}});check(r.status===200,'Authenticated daily scheduler runs');
await waitFor(async()=>await count()===4);let messages=await redis('HGETALL','toolnest:v1:messages');let overdue=messages.filter((_,i)=>i%2).map(JSON.parse).find(m=>m.kind==='overdue');
check(overdue.body.includes('Current fine: ₹50'),'Overdue notice contains calculated fine');
const receipt={entry:[{changes:[{value:{metadata:{phone_number_id:'123456789'},statuses:[{id:'wamid.receipt-test',status:'delivered',biz_opaque_callback_data:overdue.id}]}}]}]};
const raw=JSON.stringify(receipt);const sig='sha256='+createHmac('sha256','local-meta-app-secret-1234567890').update(raw).digest('hex');
r=await fetch(base+'/api/whatsapp/webhook',{method:'POST',body:raw,headers:{'Content-Type':'application/json','x-hub-signature-256':'sha256=bad'}});check(r.status===403,'Forged delivery webhook rejected');
r=await fetch(base+'/api/whatsapp/webhook',{method:'POST',body:raw,headers:{'Content-Type':'application/json','x-hub-signature-256':sig}});check(r.status===200,'Signed delivery webhook accepted');
check(JSON.parse(await redis('HGET','toolnest:v1:messages',overdue.id)).status==='delivered','Verified receipt changes message to delivered');
r=await staff.req(`/api/bookings/${id}`,{action:'return'});check(r.status===200&&r.data.booking.status==='previous'&&r.data.booking.fineAtReturn===50,'Return freezes final fee');
await staff.req('/api/staff',{});check(await count()===4,'No new notification after return');
r=await a.req('/api/account',{action:'logout'});check(r.status===200,'Logout succeeds');
r=await a.req('/api/bookings');check(r.status===401,'Logout invalidates the server session');
console.log(`Completed ${assertions} integration checks. Meta transport was mocked; no WhatsApp messages sent.`);
