import { Wrench, ArrowUpRight } from "lucide-react";
export const metadata={title:"Connect WhatsApp | Toolnest"};
export default function Setup(){return <main className="min-h-screen bg-slate-50 px-5 py-12 text-slate-900"><div className="mx-auto max-w-3xl"><a href="/" className="flex items-center gap-2 text-xl font-extrabold text-blue-700"><Wrench/> Toolnest</a><h1 className="mt-10 text-4xl font-black">Connect WhatsApp</h1><p className="mt-4 text-lg leading-8 text-slate-600">The website is prepared for Meta WhatsApp Business. Complete these steps to activate live accounts and automatic messages.</p><div className="mt-8 space-y-5">{[
  ["1","Create the WhatsApp Business app","Open Meta for Developers, create a business app and add WhatsApp. In API Setup, add and verify your own mobile number as a test recipient. Meta provides a test sending number.","https://developers.facebook.com/apps/","Open Meta for Developers"],
  ["2","Connect the account database","In the Toolnest Vercel project, open Storage and create an Upstash Redis database. Connect it to Production so registration, bookings and notification records are saved securely.","https://vercel.com/dashboard","Open Vercel"],
  ["3","Approve the four message templates","Create the four utility templates from the repository setup guide in WhatsApp Manager: order confirmation, pickup confirmation, return reminder and overdue notice. Their names, language and variables must match the guide.","https://business.facebook.com/wa/manage/message-templates/","Open WhatsApp Manager"],
  ["4","Save the connection settings","Add the Meta access token, phone number ID, app secret, API version, webhook verification token, staff password and scheduler secret in Vercel → Settings → Environment Variables. Use the complete list in the setup guide. Keep credentials out of chats and GitHub.","https://github.com/mohansolanki2006-stack/toolnest-rentals/blob/main/docs/WHATSAPP_SETUP.md","Read the setup guide"],
  ["5","Connect delivery receipts and test","Redeploy the website. Add /api/whatsapp/webhook on your website as the Meta webhook URL and subscribe to messages. Register, log in and place one test booking using your verified test number. Confirm pickup from the staff desk; check actual delivery in WhatsApp.","/manage","Open staff desk"],
].map(([number,title,description,href,label])=><section key={number} className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-extrabold">{title}</h2><p className="mt-3 text-base leading-7 text-slate-600">{description}</p><a href={href} className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-blue-700">{label}<ArrowUpRight size={16}/></a></section>)}</div><div className="mt-8 rounded-2xl bg-blue-50 p-6 text-blue-950"><h2 className="font-bold">For your college presentation</h2><p className="mt-2 leading-7">Until setup is complete, select “Try presentation demo” on the registration screen. Register, log in, book a tool and use the presentation controls to show pickup, a reminder, an overdue fine and return. Demo messages stay on the website.</p><p className="mt-3 text-sm leading-6">Live scheduled checks run daily, around 9:00 AM IST. They continue even when the website is closed. Return time is 6:00 PM IST; the default fine is ₹50 per started 24 hours late.</p></div></div></main>;}
