"use client";
import { MessageCircle, CheckCheck, Clock, AlertCircle } from "lucide-react";
import { messageTitles, dueLabel, calculateFine, type Booking, type RentalMessage } from "@/lib/rental";
const labels:Record<RentalMessage["status"],string>={preview:"Preview only • not sent",queued:"Waiting to send",sending:"Sending",accepted:"Accepted by WhatsApp",sent:"Sent",delivered:"Delivered",read:"Read",failed:"Delivery failed",unknown:"Delivery unconfirmed",skipped:"Not sent • no longer needed"};
export function RentalMessages({booking,messages,connected,demo,onDemoAction}:{booking:Booking;messages:RentalMessage[];connected:boolean;demo:boolean;onDemoAction?:(action:"pickup"|"reminder"|"overdue"|"return")=>void}){
  const fine=calculateFine(booking,booking.simulatedNow??Date.now());
  return <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white text-left">
    <div className="border-b border-slate-100 p-5"><div className="flex items-center gap-2 text-lg font-extrabold text-emerald-800"><MessageCircle size={22}/> WhatsApp updates</div><p className="mt-2 text-sm text-slate-600">{booking.whatsappConsent?`Notifications for ${booking.customerPhone}`:"WhatsApp notifications were not selected during registration."}</p>{booking.whatsappConsent&&!connected&&!demo&&<p className="mt-2 text-sm text-amber-700">WhatsApp is not connected yet. Messages are waiting; none have been sent.</p>}{demo&&<p className="mt-2 text-sm text-amber-700">Presentation preview. These messages are not sent to a phone.</p>}</div>
    <div className="grid gap-4 border-b border-slate-100 bg-slate-50 p-5 sm:grid-cols-2"><div><p className="text-sm text-slate-500">Return deadline</p><p className="mt-1 font-bold">{dueLabel(booking)}</p></div><div><p className="text-sm text-slate-500">Late return fee</p><p className="mt-1 font-bold">₹{booking.lateFeePerDay} / started 24 hours</p>{fine.amount>0&&<p className="mt-1 font-bold text-red-700">{booking.status==="previous"?"Final":"Current"} fine: ₹{fine.amount} ({fine.days} day{fine.days!==1?"s":""})</p>}</div></div>
    <div className="space-y-4 bg-[#f2f7f5] p-5">{messages.length?messages.map(m=><article key={m.id} className="rounded-xl rounded-tl-none border border-emerald-100 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-bold text-emerald-800">{messageTitles[m.kind]}</h3><span className="text-xs text-slate-500">{new Date(m.createdAt).toLocaleString("en-IN",{timeZone:"Asia/Kolkata",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})} IST</span></div><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-700">{m.body}</p><p className={`mt-3 flex items-center gap-1.5 text-xs font-semibold ${["failed","unknown"].includes(m.status)?"text-red-600":"text-slate-500"}`}>{["read","delivered"].includes(m.status)?<CheckCheck size={16}/>:m.status==="failed"?<AlertCircle size={15}/>:<Clock size={14}/>} {labels[m.status]}</p>{m.error&&<p className="mt-1 text-xs text-slate-500">{m.error}</p>}</article>):<p className="text-sm text-slate-500">Booking updates will appear here.</p>}</div>
    {demo&&onDemoAction&&<div className="border-t border-slate-200 p-5"><h3 className="font-bold">Presentation controls</h3><p className="mt-1 text-sm leading-6 text-slate-500">Simulate pickup, the reminder and an overdue return to demonstrate the full journey.</p><div className="mt-4 flex flex-wrap gap-2">{booking.status==="upcoming"&&<button onClick={()=>onDemoAction("pickup")} className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">Simulate pickup</button>}{booking.status==="active"&&<><button onClick={()=>onDemoAction("reminder")} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-bold">Preview due reminder</button><button onClick={()=>onDemoAction("overdue")} className="rounded-lg border border-amber-300 bg-amber-50 px-4 py-2.5 text-sm font-bold text-amber-900">{fine.days?"Add another overdue day":"Simulate 1 day overdue"}</button><button onClick={()=>onDemoAction("return")} className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Confirm demo return</button></>}</div></div>}
  </section>;
}
